apiVersion: v1
kind: Service
metadata:
  name: juice-service
  namespace: default
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: juice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice
  namespace: default
spec:
  selector:
    matchLabels:
      app: juice
  template:
    metadata:
      labels:
        app: juice
    spec:
      containers:
      - name: juice
        image: bkimminich/juice-shop
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: juice-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: juice-route
spec:
  parentRefs:
  - name: juice-gateway
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: juice-service
      port: 80
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: juice-backend-policy
  namespace: default
spec:
  default:
    securityPolicy: "juice-ca-policy"
    logging:
      enabled: true
      sampleRate: 500000
  targetRef:
    group: ""
    kind: Service
    name: juice-service