apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gxmlb-gateway
  namespace: default
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: default
spec:
  parentRefs:
  - name: gxmlb-gateway
  rules:
  - matches:
      - path:
            type: PathPrefix # Type of path match (prefix-based matching)
            value: /
    filters:
        - type: RequestHeaderModifier  # Type of filter applied to the route (modifying request headers)
          requestHeaderModifier:
            add: # Add header
              - name: "x-new-header"
                value: "This-is-new-header"
            set: # Modify header
              - name: "x-site-env"
                value: "test-modified-value"
            remove: ["x-delete-header"] # Delete header
    backendRefs: 
      - name: test-site-service
        port: 80 
  - backendRefs:
      - name: test-site-service
        port: 80