apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gxmlb-gateway
  namespace: default
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      kinds:
      - kind: HTTPRoute
      namespaces:
          from: Same
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: test-route
  namespace: default
spec:
  parentRefs:
  - name: gxmlb-gateway
  rules:
  - matches:
      - headers:
          - name: X-Site-Env
            value: "test"   
            type: Exact  
    backendRefs: 
      - name: test-site-service
        port: 80 
  - matches:
      - headers:
          - name: X-Site-Env
            value: "prod"
            type: Exact
    backendRefs:
      - name: prod-site-service
        port: 80
  - backendRefs:
      - name: test-site-service
        port: 80